### ISSUE TITLE
Encoder instead of Decoder

### ISSUE THREAD

**Issue by sonukiller** [oneformer3d/oneformer3d#15]
You have used a decoder architecture, what do you think about using an encoder instead?

**Comment by filaPro** [comment]
I think, for ScanNet it is possible to use encoder as we initialize queries with all superpoints. However for S3DIS i don't have good ideas how to use only encoder, as we use ~100 queries and need cross-attention to thousands of point-cloud features.

**Comment by sonukiller** [comment]
I believe that a decoder is much more useful when a sequence is important; in this case, it is not (point cloud is irregular). So the use of an encoder will be a good choice, what do you think?
