### ISSUE TITLE
Implementation on windows

### ISSUE THREAD

**Issue by BaptFontaine** [oneformer3d/oneformer3d#20]
I tried running your test script on the s3dis dataset but ran into trouble installing MinkowskiEngine on Windows. When I attempted to install it, I got a message saying it's not supported on Windows. This happened in the oneformer3d.py file.
I'm on Windows 10 with Torch 1.13 and CUDA 11.6. Could you provide guidance on how to either install MinkowskiEngine on Windows or suggest an alternative solution that doesn't require it?

Thank you for your really interesting work

**Comment by BaptFontaine** [comment]
Thank you for your response. I will try to figure it out, but it seems that the Minkowski Engine isn't suitable for Windows. 

I have another question regarding continuing to build my implementation. Your configuration file from S3DISOneformer refers to a SpConvUNet backbone model, but I can't figure out where to find it. Could you please tell me where it comes from?

**Comment by filaPro** [comment]
I think [here](https://github.com/filaPro/oneformer3d/blob/main/oneformer3d/spconv_unet.py#L95).

**Comment by BaptFontaine** [comment]
Hi, I attempted to utilize SpConv for the S3DISOneFormer3D.collate function, but I am unsure how to correctly replace lines 323 and 324. Is there an easy solution to replace these lines with SpConv?

**Comment by filaPro** [comment]
One way is probably to use SPFomer [code](https://github.com/sunjiahao1999/SPFormer/blob/main/spformer/dataset/scannetv2.py#L259) as we adapt exactly the same pre-trained backbone as they for ScanNet. So their pre-processing without MinkowskiEngine is exactly the same as ours.
