### ISSUE TITLE
CUDA Memory not enough

### ISSUE THREAD

**Issue by boxiao-wv** [oneformer3d/oneformer3d#24]
Dear filaPro,

Thanks for the amazing work! I am trying to train on S3DIS dataset, however, the training always breaks at around epoch 15 due to not enough cuda memory. I have a RTX4090 with 24GB memory. Could you provide some hints of how to adjust the config file to let the training fit into 24GB memory?

Thanks a lot!

**Comment by filaPro** [comment]
1. yes predicted masks may intersect
2. in pts_semantic_mask we keep semantic predictions for semantic and panoptic segmentation; in pts_instance_mask we keep instance predictions for instance and panoptic segmentation. each of these 4 things is (a bit) different from one another
3. just keep the predictions with instance_score more than some threshold e.g. 0.3 and there will be not to much intersections. for visualization we just sort them by this score and start painting from the highest
