### ISSUE TITLE
Any proposal for lightweight Model

### ISSUE THREAD

**Issue by Beiliergo** [oneformer3d/oneformer3d#27]
Congratulations on achieving such outstanding results. I have tried to train the model, unfortunately, it seems that our training server has not been updated for a long time. Each GPU has only 12GB of memory.
Obviously model that cannot be trained in this hardware. At the same time, we hope to run the model on a single card. We can accept a decrease in performance while minimizing memory usage as much as possible. 
Can you provide a configuration file for a lightweight model? Any suggestions are welcome.

**Comment by filaPro** [comment]
Are you training on S3DIS ot on ScanNet? You can try to sample less points as an input [here](https://github.com/filaPro/oneformer3d/blob/main/configs/oneformer3d_1xb2_s3dis-area-5.py#L100). This `PointSample_` can also be added to other configs.
