### ISSUE TITLE
Where is the code generated by the superpoint？

### ISSUE THREAD

**Issue by jing-zhao9** [oneformer3d/oneformer3d#33]
I referred to the S3DIS preprocessing section in readme, but did not see the code for generating superpoints. In the model, it seems that the number of superpoints in each room of the S3DIS dataset is unique, 413

**Comment by oneformer3d-contributor** [comment]
Hi @jing-zhao9 ,
Actually we don't use superpoints for s3dis, with cross-attention directly to voxel features.

**Comment by RayYoh** [comment]
> Hi @jing-zhao9 , Actually we don't use superpoints for s3dis, with cross-attention directly to voxel features.

I read the code and found that there are two loss functions in S3DISOneFormer3D and didn't see query selection. Also, in the config file for S3DIS, instead of SparseMatcher, HungarianMatcher is used. Does it mean, for S3DIS just incorporate SPFormer into Oneformer?

**Comment by oneformer3d-contributor** [comment]
Mainly yes. May be 2 differences: we also solve semantic segmentation, we don't use superpoints on S3DIS.

**Comment by RayYoh** [comment]
> Mainly yes. May be 2 differences: we also solve semantic segmentation, we don't use superpoints on S3DIS.

OK, got that, Thanks for your reply.
