### ISSUE TITLE
how to modify the code to use it for sunrgbd dataset? 

### ISSUE THREAD

**Issue by yxchng** [oneformer3d/oneformer3d#35]
do you mind explaining the part i need to change?

**Comment by yxchng** [comment]
For 3d semantic segmentation and object detection. I wonder if it is possible to disable the instance part.

**Comment by oneformer3d-contributor** [comment]
I think for semantic segmentation it's probably much easier to use MinkowskiUNet from MinkowskiEngine instead of the whole OneFormer3D. And for object detection we don't have any training code.
