### ISSUE TITLE
How do you compute the inference time number in Table 11?

### ISSUE THREAD

**Issue by yxchng** [oneformer3d/oneformer3d#38]
Do you mind sharing the code for OneFormer3D?
![Screenshot from 2024-03-20 19-50-03](https://github.com/oneformer3d/oneformer3d/assets/10518587/26486b11-bd2a-4f19-bfde-3325a6b4ffc7)

**Comment by oneformer3d-contributor** [comment]
You can simply add `time.time()` calls between these 4 parts of out method and then average the times throw the validation run.
