### ISSUE TITLE
wrong log given for s3dis?

### ISSUE THREAD

**Issue by yxchng** [oneformer3d/oneformer3d#41]
The log given on the right does not match the metrics reported on the left. There isn't any entry that gives mAP@0.25 of 80.6.

![Screenshot from 2024-03-21 11-35-54](https://github.com/oneformer3d/oneformer3d/assets/10518587/4def9471-1644-4a74-bdbe-30681aa71f35)

**Comment by oneformer3d-contributor** [comment]
Yes, sorry for this. This is for epoch 51 in the log file, and 2 or 3 inference parameters are different. Please compare `test_cfg` in `.py` config and in `.log` file. The difference is less than 1%, it is just to reduce the resources during validation.

**Comment by yxchng** [comment]
@oneformer3d-contributor which params can give the reported results? the one in `.py` or `.log`?

**Comment by oneformer3d-contributor** [comment]
Metrics in the `readme` are for provided `.py` config and the checkpoint.
