### ISSUE TITLE
Query about a minor difference between ScanNet and ScanNet200

### ISSUE THREAD

**Issue by RayYoh** [oneformer3d/oneformer3d#43]
Hi, authors, thanks for your work.

I have one question about `ScanNet200OneFormer3D` and `ScanNetOneFormer3D`. In the code, for Scannet use the `inverse_mapping` [here](https://github.com/oneformer3d/oneformer3d/blob/9d52edfc7089ccf7f26f32d2ec63d1ab8d4338ca/oneformer3d/oneformer3d.py#L291) to map the voxel but for ScanNet200, why not use the mapping [here](https://github.com/oneformer3d/oneformer3d/blob/9d52edfc7089ccf7f26f32d2ec63d1ab8d4338ca/oneformer3d/oneformer3d.py#L516).

**Comment by oneformer3d-contributor** [comment]
Unfortunately ScanNet model is on SpConv backbone and ScanNet200 is on MinkowskiEngine. The notation of point <-> voxel correspondence is a bit different in this packages. Regarding you question for ScanNet200 inverse mapping thing is done in a previous [line](https://github.com/oneformer3d/oneformer3d/blob/9d52edfc7089ccf7f26f32d2ec63d1ab8d4338ca/oneformer3d/oneformer3d.py#L508).
