### ISSUE TITLE
3d box detection? 

### ISSUE THREAD

**Issue by jiachen0212** [oneformer3d/oneformer3d#44]
hello， thanks for your work~
However, I encountered some problems when using 3D point cloud detection~ I would like to ask, does your work support 3D detection and output box and orientation? I followed the scannet data format step by step, but encountered this bug ~
![1711341586091](https://github.com/oneformer3d/oneformer3d/assets/29834982/c389b1e0-3140-4666-9570-cbbfaf236205)
![lQDPJwiCFmwGrY12zQHhsHe8JRhVC8G5Be6YYfUh9gA_481_118](https://github.com/oneformer3d/oneformer3d/assets/29834982/ccbef3fd-f0d3-4290-83f3-50f6d9383e26)
![lQDPKHdus1Jjjo3MrM0Bg7ADQZi28amhfwXumGJ154UA_387_172](https://github.com/oneformer3d/oneformer3d/assets/29834982/c498bca4-68e8-4274-af60-cb6c82c6f30b)

**Comment by filaPro** [comment]
Please follow #21.

**Comment by oneformer3d-contributor** [comment]
At training stage this repo has nothing to do with object detection. However on test stage the object detection can be done simply with mapping each predicted instance with the smallest axis-aligned bounding box. The idea how to do it is described in #21.

**Comment by jiachen0212** [comment]
> At training stage this repo has nothing to do with object detection. However on test stage the object detection can be done simply with mapping each predicted instance with the smallest axis-aligned bounding box. The idea how to do it is described in #21.



Thank you very much for your reply. I modified 3 codes according to #21, with_bbox_3d=False during train and with_bbox_3d=True during test. But I still get this bug..
![Uploading image.png…]()

**Comment by oneformer3d-contributor** [comment]
Please import `DepthInstance3DBoxes` from `mmdet3d.structures`.
