### ISSUE TITLE
Minkowski vs SpConv Backbone

### ISSUE THREAD

**Issue by YilmazKadir** [oneformer3d/oneformer3d#45]
When do you use the Minkowski backbone and when do you use the SpConv backbone? Also, there are some differences between the two such as the number of blocks and the number of planes for the two convolutional backbones. Why is this the case? Do they perform similarly?

**Comment by oneformer3d-contributor** [comment]
Just to start training from SSTNet or Mask3D checkpoint. For some reason on of them is better on ScanNet, other on ScanNet200...
