### ISSUE TITLE
Why voxelize in `collate` instead of using the `voxel` option in Det3DDataPreprocessor from mmdet3d?

### ISSUE THREAD

**Issue by yxchng** [oneformer3d/oneformer3d#47]
Is there any particular reason why you choose to rewrite voxelization in `collate` function instead of using the officially supported mmdet3d's `voxel`? Are there any difference between the two?

https://github.com/oneformer3d/oneformer3d/blob/9d52edfc7089ccf7f26f32d2ec63d1ab8d4338ca/oneformer3d/oneformer3d.py#L297

**Comment by filaPro** [comment]
Should be the same actually. We just followed our previous works here, e.g. fcaf3d and tr3d.

**Comment by oneformer3d-contributor** [comment]
Should be the same actually. We just followed our previous works here, e.g. fcaf3d and tr3d.
