### ISSUE TITLE
bug in fix_spconv_checkpoint?

### ISSUE THREAD

**Issue by AaronNZH** [oneformer3d/oneformer3d#52]
Should the 17th line of the code in fix_spconv_checkpoint be changed to the following code?
checkpoint[key][layer] = checkpoint[key][layer].permute(3, 4, 0, 1, 2)

I printed the shape of scannet pretrained parameter and model parameters, and got the following results 
(consisting of layer name, shape in ckpt, shape in model):

unet.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 32, 32, 3])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 32, 32, 3])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 32, 32, 3])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 32, 32, 3])
cur torch.Size([32, 3, 3, 3, 32])
unet.conv.2.weight
ckpt torch.Size([2, 2, 32, 64, 2])
cur torch.Size([64, 2, 2, 2, 32])
unet.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 64, 64, 3])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 64, 64, 3])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 64, 64, 3])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 64, 64, 3])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.conv.2.weight
ckpt torch.Size([2, 2, 64, 96, 2])
cur torch.Size([96, 2, 2, 2, 64])
unet.u.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 96, 96, 3])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 96, 96, 3])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 96, 96, 3])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 96, 96, 3])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.conv.2.weight
ckpt torch.Size([2, 2, 96, 128, 2])
cur torch.Size([128, 2, 2, 2, 96])
unet.u.u.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 128, 128, 3])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 128, 128, 3])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 128, 128, 3])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 128, 128, 3])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.conv.2.weight
ckpt torch.Size([2, 2, 128, 160, 2])
cur torch.Size([160, 2, 2, 2, 128])
unet.u.u.u.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 160, 160, 3])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 160, 160, 3])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 160, 160, 3])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 160, 160, 3])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.deconv.2.weight
ckpt torch.Size([2, 2, 160, 128, 2])
cur torch.Size([128, 2, 2, 2, 160])
unet.u.u.u.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 256, 128, 1])
cur torch.Size([128, 1, 1, 1, 256])
unet.u.u.u.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 256, 128, 3])
cur torch.Size([128, 3, 3, 3, 256])
unet.u.u.u.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 128, 128, 3])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 128, 128, 3])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 128, 128, 3])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.deconv.2.weight
ckpt torch.Size([2, 2, 128, 96, 2])
cur torch.Size([96, 2, 2, 2, 128])
unet.u.u.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 192, 96, 1])
cur torch.Size([96, 1, 1, 1, 192])
unet.u.u.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 192, 96, 3])
cur torch.Size([96, 3, 3, 3, 192])
unet.u.u.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 96, 96, 3])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 96, 96, 3])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 96, 96, 3])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.deconv.2.weight
ckpt torch.Size([2, 2, 96, 64, 2])
cur torch.Size([64, 2, 2, 2, 96])
unet.u.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 128, 64, 1])
cur torch.Size([64, 1, 1, 1, 128])
unet.u.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 128, 64, 3])
cur torch.Size([64, 3, 3, 3, 128])
unet.u.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 64, 64, 3])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 64, 64, 3])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 64, 64, 3])
cur torch.Size([64, 3, 3, 3, 64])
unet.deconv.2.weight
ckpt torch.Size([2, 2, 64, 32, 2])
cur torch.Size([32, 2, 2, 2, 64])
unet.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 64, 32, 1])
cur torch.Size([32, 1, 1, 1, 64])
unet.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 64, 32, 3])
cur torch.Size([32, 3, 3, 3, 64])
unet.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 32, 32, 3])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 32, 32, 3])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 32, 32, 3])
cur torch.Size([32, 3, 3, 3, 32])
input_conv.0.weight
ckpt torch.Size([3, 3, 6, 32, 3])
cur torch.Size([32, 3, 3, 3, 6])

**Comment by AaronNZH** [comment]
Oh, I'm sorry. The question should be changed to:

Should the 17th line of the code in fix_spconv_checkpoint be changed to the following code?
checkpoint[key][layer] = checkpoint[key][layer].permute(4, 0, 1, 2, 3)

I printed the shape of scannet pretrained parameter and model parameters, and got the following results
(consisting of layer name, shape in ckpt, shape in model):

unet.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 32, 32])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 32, 32])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 32, 32])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 32, 32])
cur torch.Size([32, 3, 3, 3, 32])
unet.conv.2.weight
ckpt torch.Size([2, 2, 2, 32, 64])
cur torch.Size([64, 2, 2, 2, 32])
unet.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 64, 64])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 64, 64])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 64, 64])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 64, 64])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.conv.2.weight
ckpt torch.Size([2, 2, 2, 64, 96])
cur torch.Size([96, 2, 2, 2, 64])
unet.u.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 96, 96])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 96, 96])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 96, 96])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 96, 96])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.conv.2.weight
ckpt torch.Size([2, 2, 2, 96, 128])
cur torch.Size([128, 2, 2, 2, 96])
unet.u.u.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 128, 128])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 128, 128])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 128, 128])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 128, 128])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.conv.2.weight
ckpt torch.Size([2, 2, 2, 128, 160])
cur torch.Size([160, 2, 2, 2, 128])
unet.u.u.u.u.blocks.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 160, 160])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.u.blocks.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 160, 160])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.u.blocks.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 160, 160])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.u.blocks.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 160, 160])
cur torch.Size([160, 3, 3, 3, 160])
unet.u.u.u.deconv.2.weight
ckpt torch.Size([2, 2, 2, 160, 128])
cur torch.Size([128, 2, 2, 2, 160])
unet.u.u.u.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 1, 256, 128])
cur torch.Size([128, 1, 1, 1, 256])
unet.u.u.u.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 256, 128])
cur torch.Size([128, 3, 3, 3, 256])
unet.u.u.u.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 128, 128])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 128, 128])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.u.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 128, 128])
cur torch.Size([128, 3, 3, 3, 128])
unet.u.u.deconv.2.weight
ckpt torch.Size([2, 2, 2, 128, 96])
cur torch.Size([96, 2, 2, 2, 128])
unet.u.u.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 1, 192, 96])
cur torch.Size([96, 1, 1, 1, 192])
unet.u.u.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 192, 96])
cur torch.Size([96, 3, 3, 3, 192])
unet.u.u.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 96, 96])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 96, 96])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.u.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 96, 96])
cur torch.Size([96, 3, 3, 3, 96])
unet.u.deconv.2.weight
ckpt torch.Size([2, 2, 2, 96, 64])
cur torch.Size([64, 2, 2, 2, 96])
unet.u.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 1, 128, 64])
cur torch.Size([64, 1, 1, 1, 128])
unet.u.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 128, 64])
cur torch.Size([64, 3, 3, 3, 128])
unet.u.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 64, 64])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 64, 64])
cur torch.Size([64, 3, 3, 3, 64])
unet.u.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 64, 64])
cur torch.Size([64, 3, 3, 3, 64])
unet.deconv.2.weight
ckpt torch.Size([2, 2, 2, 64, 32])
cur torch.Size([32, 2, 2, 2, 64])
unet.blocks_tail.block0.i_branch.0.weight
ckpt torch.Size([1, 1, 1, 64, 32])
cur torch.Size([32, 1, 1, 1, 64])
unet.blocks_tail.block0.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 64, 32])
cur torch.Size([32, 3, 3, 3, 64])
unet.blocks_tail.block0.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 32, 32])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks_tail.block1.conv_branch.2.weight
ckpt torch.Size([3, 3, 3, 32, 32])
cur torch.Size([32, 3, 3, 3, 32])
unet.blocks_tail.block1.conv_branch.5.weight
ckpt torch.Size([3, 3, 3, 32, 32])
cur torch.Size([32, 3, 3, 3, 32])
input_conv.0.weight
ckpt torch.Size([3, 3, 3, 6, 32])
cur torch.Size([32, 3, 3, 3, 6])

**Comment by oneformer3d-contributor** [comment]
I think our pretrained models are already reshaped, so you don't need to run the script for them.

**Comment by AaronNZH** [comment]
I use the weight download from 
https://github.com/oneformer3d/oneformer3d/releases/download/v1.0/oneformer3d_1xb4_scannet.pth
and get mismatch size errors.

**Comment by oneformer3d-contributor** [comment]
do you use `spconv-cu116==2.3.6`?

**Comment by AaronNZH** [comment]
> do you use `spconv-cu116==2.3.6`?

yes

**Comment by oneformer3d-contributor** [comment]
and this version of mmdet3d `git+https://github.com/open-mmlab/mmdetection3d.git@22aaa47fdb53ce1870ff92cb7e3f96ae38d17f61`?

**Comment by AaronNZH** [comment]
> and this version of mmdet3d `git+https://github.com/open-mmlab/mmdetection3d.git@22aaa47fdb53ce1870ff92cb7e3f96ae38d17f61`?
I didn't use mmdetection. I simply copy the model file and build a new model based on it.

**Comment by oneformer3d-contributor** [comment]
than probably in your case you need the reshape, that is in your question. for our case i think the script is fine

**Comment by AaronNZH** [comment]
Got it, thanks for your help
