### ISSUE TITLE
该如何拿到点云分割的中间结果，而不只是metrics的结果？

### ISSUE THREAD

**Issue by 1163710216** [oneformer3d/oneformer3d#53]

**Comment by filaPro** [comment]
Hi @1163710216 ,
Unfortunately i don't know Chinese. But you want to visualize semantic, instance and panoptic masks you can get them at the [end](https://github.com/oneformer3d/oneformer3d/blob/main/oneformer3d/oneformer3d.py#L419) of `predict` function, and the colored input points at the [beginning](https://github.com/oneformer3d/oneformer3d/blob/main/oneformer3d/oneformer3d.py#L407) of `predict` function.

**Comment by oneformer3d-contributor** [comment]
Hi @1163710216 ,
Unfortunately i don't know Chinese. But you want to visualize semantic, instance and panoptic masks you can get them at the [end](https://github.com/oneformer3d/oneformer3d/blob/main/oneformer3d/oneformer3d.py#L419) of `predict` function, and the colored input points at the [beginning](https://github.com/oneformer3d/oneformer3d/blob/main/oneformer3d/oneformer3d.py#L407) of `predict` function.
