### ISSUE TITLE
what is the meaning of num_instance_classes

### ISSUE THREAD

**Issue by iris0329** [oneformer3d/oneformer3d#56]
for s3dis dataset, num_semantic_classes is same as  num_instance_classes; 
However, for scannet200, num_instance_classes is 198, and num_semantic_classes is 200. 
Can I just set num_instance_classes to 200? what's the difference?

**Comment by oneformer3d-contributor** [comment]
There are 2 classes in ScanNet that don't participate in instance segmentation: `floor` and `wall`. However for S3DIS all 13 classes are both in instance and semantic benchmarks.
