### ISSUE TITLE
Using oneformer3d for semantic segmentation only

### ISSUE THREAD

**Issue by boxiao-wv** [oneformer3d/oneformer3d#59]
I wonder whether there is a configuration template for purely semantic segmentation only? I understand that the current template outputs instance, semantic and panoptic segmentation results. Is there an easy way to disable the instance and panoptic segmentation parts?

Thank you very much!

**Comment by oneformer3d-contributor** [comment]
I think the easiest way is to set instance loss wieght to 0. Otherwise you need to modify the decoder (remove instance queries) and loss (remove instance loss).
