### ISSUE TITLE
save the results

### ISSUE THREAD

**Issue by ustbwang1jie** [oneformer3d/oneformer3d#66]
Thank you very much for your project. While reproducing the work, I wanted to save the results. However, during the testing process, I found that/work_dirs/timestamp/show_dir/did not save anything. May I know what command I can use to run test.py

**Comment by oneformer3d-contributor** [comment]
We don't add visualization in this repo. Please look at #57, #14.

**Comment by ustbwang1jie** [comment]
Thanks for your kind reply!
