### ISSUE TITLE
Perform Instance Segmentation on a single .ply file.

### ISSUE THREAD

**Issue by athanzxyt** [oneformer3d/oneformer3d#67]
Hi!

I'm a bit confused with the readme and not sure how to proceed. I'm trying to use this model for a school project, how can I adapt this repository to perform semantic instance segmentation on a single .ply file.

**Comment by oneformer3d-contributor** [comment]
Unfortunately we have no valid script for it. Please looks at #9, #57.

**Comment by athanzxyt** [comment]
I'm still confused after reading through those previous issues. Are you saying its not possible to perform inference using the model weights you've already provided?

I don't want to train or test the model extensively, I only need to perform small inference.

**Comment by oneformer3d-contributor** [comment]
It is possible. You can simply do smth like `build_model(config)(pcd)`. Where `pcd` is an array of `n_points, 6` for `(x, y, z, r, g, b)`. Just copy the model part from our s3dis config and be sure that input point cloud is normalised in the same way as in our s3dis config.

**Comment by athanzxyt** [comment]
Where does `build_model` come from, I don't see it in either this or the mmdetection repos
