### ISSUE TITLE
The code and config about submission of test benchmark

### ISSUE THREAD

**Issue by wdczz** [oneformer3d/oneformer3d#68]
Dear authors, thank you for your great work. I would like to ask whether you can share the code and config about processing the result for submission the test benchmark?
Thank you very much.

**Comment by wdczz** [comment]
Thank you for your response. Can you please guide me on how to configure the submission? This is my first time using the MMLAB framework. QAQ

**Comment by wdczz** [comment]
I finished the code for SPInstanceSegMetric, but I'm confused about how to set the configuration.  Looking forward to your guidance！

**Comment by oneformer3d-contributor** [comment]
Just add `ann_file='scannet_oneformer3d_infos_test.pkl'` instead of `ann_file='scannet_oneformer3d_infos_val.pkl'` for `test_dataloader` in ScanNet config file.

**Comment by jeff2048** [comment]
> Just add `ann_file='scannet_oneformer3d_infos_test.pkl'` instead of `ann_file='scannet_oneformer3d_infos_val.pkl'` for `test_dataloader` in ScanNet config file.

Dear Author,

I am a little confused about what you mentioned [here](https://github.com/filaPro/oneformer3d/issues/63#issuecomment-2178239073). You mentioned starting from the same SSTNet checkpoint and then training OneFormer3D on the train + val sets. Does this mean that, when submitting to the hidden test benchmark, we need to retrain the model using both train.pkl and val.pkl? If so, could you please clarify how to modify the training configuration in the train loader? Thank you for your guidance!

**Comment by filaPro** [comment]
Hi @jeff2048 ,

Actually, i don't remember, if we did it. But probably, yes, for the best submission we trained on train + val. You can just use ConcatDataset for this purpose, like [here](https://github.com/filaPro/oneformer3d/blob/main/configs/oneformer3d_1xb2_s3dis-area-5.py#L159).

**Comment by jeff2048** [comment]
> Hi @jeff2048 ,
> 
> Actually, i don't remember, if we did it. But probably, yes, for the best submission we trained on train + val. You can just use ConcatDataset for this purpose, like [here](https://github.com/filaPro/oneformer3d/blob/main/configs/oneformer3d_1xb2_s3dis-area-5.py#L159).

Thank you so much!
