### ISSUE TITLE
Error submission on scannet test benchmark 

### ISSUE THREAD

**Issue by FirstHeart01** [oneformer3d/oneformer3d#69]
Dear authors, thank you for your excellent job! 

I submit the test results for 3D Semantic Instace Benchmark Task. But I faild to finish evaluation, the email told me '"Reason: Extraction of the submitted archive timed out. The system thinks that the problem is due to invalid input." 

I looked at my txt files and I think it should be fine.  Could it be that the file I submitted was originally over 12G in size or the directory structure of my zip file is not correct?  I'd appreciate it if you could help me.

My results like this.
![structure](https://github.com/user-attachments/assets/abe13ade-9d7e-45ff-b981-52337ca418ca)

**Comment by wdczz** [comment]
请问可以分享一下怎么设置提交的config吗QAQ

**Comment by oneformer3d-contributor** [comment]
For significant decrease of the archive size w/o decreasing of metrics you can increase `inst_score_thr` in the config to 0.01 or something like this.

**Comment by FirstHeart01** [comment]
> For significant decrease of the archive size w/o decreasing of metrics you can increase `inst_score_thr` in the config to 0.01 or something like this.

So is this actually because of the size of the archive?

**Comment by FirstHeart01** [comment]
> 请问可以分享一下怎么设置提交的config吗QAQ

你只需要把数据集的pipeline改变，只输入点云数据(或者还要包括超点)，然后进行模型的推理应该就可以了。

**Comment by oneformer3d-contributor** [comment]
> So is this actually because of the size of the archive?

I don't remember, but 12Gb sounds much bigger, then we submitted.

**Comment by wdczz** [comment]
> > 请问可以分享一下怎么设置提交的config吗QAQ
> 
> 你只需要把数据集的pipeline改变，只输入点云数据(或者还要包括超点)，然后进行模型的推理应该就可以了。

我们可以邮件联系吗

**Comment by FirstHeart01** [comment]
> > So is this actually because of the size of the archive?
> 
> I don't remember, but 12Gb sounds much bigger, then we submitted.

OK, I will submit again. I think it's because the big size of my original files before compressed(I originally thought that the uploaded zip file could not exceed 12Gb)

thanks very much.

**Comment by Dovisya** [comment]
> Dear authors, thank you for your excellent job!
> 
> I submit the test results for 3D Semantic Instace Benchmark Task. But I faild to finish evaluation, the email told me '"Reason: Extraction of the submitted archive timed out. The system thinks that the problem is due to invalid input."
> 
> I looked at my txt files and I think it should be fine. Could it be that the file I submitted was originally over 12G in size or the directory structure of my zip file is not correct? I'd appreciate it if you could help me.
> 
> My results like this. ![structure](https://github.com/user-attachments/assets/abe13ade-9d7e-45ff-b981-52337ca418ca)

The data structure in the detection result compressed package submitted by me and you is the same, but the detection website prompts me to detect failure: Reason: Extra subfolder in results folder in archive: submission_scannet_inst. Here submission_scannet_inst is the name of my submission folder.
